#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

if [ "$1" == "php-fpm" ]; then
    /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
fi

exec "$@"
